project:
  type: website

website:
  google-analytics:
    tracking-id: "G-CEC6152V08"
    anonymize-ip: true
  favicon: logo.png
  title: "Marcell Granat"
  navbar:
    
    right:
      # - about.qmd
      - icon: bar-chart-line
        text: Big Data & Visualisation
        href: https://marcellgranat.com/bigdata
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/granatmarcell
      - icon: github
        text: GitHub
        href: https://github.com/MarcellGranat
      - icon: file-earmark-person
        text: CV
        href: https://marcellgranat.github.io/cv/
      - icon: envelope
        href: "mailto:granat.marcell@uni-neumann.hu"
format:
  html:
    theme: [darkly, styles.scss]

editor: visual

